name: futbol_analiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  foundation: ^0.0.5
  markdown_widget: ^2.3.2+8
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  csv: ^5.0.0
  unorm_dart: ^0.2.0
  provider: ^6.1.5
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  package_info_plus: 8.3.0
  fl_chart: ^1.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  palette_generator: ^0.3.3+4
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  google_nav_bar: ^5.0.6
  
  # YENİ EKLENEN PAKET
  timeline_tile: ^2.0.0
  convex_bottom_bar: ^3.2.0
  vibration: ^3.1.3
  animated_bottom_navigation_bar: ^1.4.0
  image_picker: ^1.0.7

  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/logos/leagues/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
