name: futbol_analiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  foundation: ^0.0.5
  markdown_widget: ^2.3.2+8
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  csv: ^5.0.0
  unorm_dart: ^0.2.0
  provider: ^6.1.5
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  fl_chart: ^1.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  palette_generator: ^0.3.3+4
  flutter_svg: ^2.2.0
  intl: ^0.20.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_animations: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/logos/leagues/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
