// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtp-46yLVVQBeSv80XKIyJ3JMowOz7BGU',
    appId: '1:574970005987:web:27a70e845d5c2eec0178d6',
    messagingSenderId: '574970005987',
    projectId: 'goalitycs-b4f05',
    authDomain: 'goalitycs-b4f05.firebaseapp.com',
    storageBucket: 'goalitycs-b4f05.firebasestorage.app',
    measurementId: 'G-DFBVL2PX26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_xXzBIHZeIg8ULGJgQeI-5bq0Fywixs',
    appId: '1:574970005987:android:201872f9126015290178d6',
    messagingSenderId: '574970005987',
    projectId: 'goalitycs-b4f05',
    storageBucket: 'goalitycs-b4f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSwhoO7k8ivo3E8lSgkqyx0414E4KPGE',
    appId: '1:574970005987:ios:f07b487c538c39db0178d6',
    messagingSenderId: '574970005987',
    projectId: 'goalitycs-b4f05',
    storageBucket: 'goalitycs-b4f05.firebasestorage.app',
    iosBundleId: 'com.example.futbolAnalizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQSwhoO7k8ivo3E8lSgkqyx0414E4KPGE',
    appId: '1:574970005987:ios:f07b487c538c39db0178d6',
    messagingSenderId: '574970005987',
    projectId: 'goalitycs-b4f05',
    storageBucket: 'goalitycs-b4f05.firebasestorage.app',
    iosBundleId: 'com.example.futbolAnalizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtp-46yLVVQBeSv80XKIyJ3JMowOz7BGU',
    appId: '1:574970005987:web:319fd1119d3976790178d6',
    messagingSenderId: '574970005987',
    projectId: 'goalitycs-b4f05',
    authDomain: 'goalitycs-b4f05.firebaseapp.com',
    storageBucket: 'goalitycs-b4f05.firebasestorage.app',
    measurementId: 'G-TPYP2WX7NT',
  );

}